// Copyright (c) 2021 - 2025  Intel Corporation
//
// SPDX-License-Identifier: BSD-2-Clause-Patent

// Auto-generated by `td-layout-config`, do not edit manually.

/*
Image Layout
+----------------------------------------+ <- 0x0
|                 CONFIG                 |   (0x20000) 128 kB
+----------------------------------------+ <- 0x20000
|                MAILBOX                 |   (0x1000) 4 kB
+----------------------------------------+ <- 0x21000
|               TEMP_STACK               |   (0x10000) 64 kB
+----------------------------------------+ <- 0x31000
|               TEMP_HEAP                |   (0x10000) 64 kB
+----------------------------------------+ <- 0x41000
|                  FREE                  |   (0x0) 0 B
+----------------------------------------+ <- 0x41000
|                PAYLOAD                 |   (0xF56000) 15.34 MB
+----------------------------------------+ <- 0xF97000
|                METADATA                |   (0x1000) 4 kB
+----------------------------------------+ <- 0xF98000
|                  IPL                   |   (0x60000) 384 kB
+----------------------------------------+ <- 0xFF8000
|              RESET_VECTOR              |   (0x8000) 32 kB
+----------------------------------------+ <- 0x1000000
Image size: 0x1000000 (16 MB)
*/

// Image Layout Configuration

pub const TD_SHIM_CONFIG_OFFSET: u32 = 0x0;
pub const TD_SHIM_CONFIG_SIZE: u32 = 0x20000; // 128 kB

pub const TD_SHIM_MAILBOX_OFFSET: u32 = 0x20000;
pub const TD_SHIM_MAILBOX_SIZE: u32 = 0x1000; // 4 kB

pub const TD_SHIM_TEMP_STACK_OFFSET: u32 = 0x21000;
pub const TD_SHIM_TEMP_STACK_SIZE: u32 = 0x10000; // 64 kB

pub const TD_SHIM_TEMP_HEAP_OFFSET: u32 = 0x31000;
pub const TD_SHIM_TEMP_HEAP_SIZE: u32 = 0x10000; // 64 kB

pub const TD_SHIM_FREE_OFFSET: u32 = 0x41000;
pub const TD_SHIM_FREE_SIZE: u32 = 0x0; // 0 B

pub const TD_SHIM_PAYLOAD_OFFSET: u32 = 0x41000;
pub const TD_SHIM_PAYLOAD_SIZE: u32 = 0xF56000; // 15.34 MB

pub const TD_SHIM_METADATA_OFFSET: u32 = 0xF97000;
pub const TD_SHIM_METADATA_SIZE: u32 = 0x1000; // 4 kB

pub const TD_SHIM_IPL_OFFSET: u32 = 0xF98000;
pub const TD_SHIM_IPL_SIZE: u32 = 0x60000; // 384 kB

pub const TD_SHIM_RESET_VECTOR_OFFSET: u32 = 0xFF8000;
pub const TD_SHIM_RESET_VECTOR_SIZE: u32 = 0x8000; // 32 kB

// Offset when Loading into Memory
pub const TD_SHIM_FIRMWARE_BASE: u32 = 0xFF000000;
pub const TD_SHIM_FIRMWARE_SIZE: u32 = 0x1000000;

// TD_SHIM_SEC_INFO_OFFSET equals to firmware size - metadata pointer offset -
// OVMF GUID table size - SEC Core information size.
pub const TD_SHIM_SEC_CORE_INFO_OFFSET: u32 = 0xFFFFAC;
pub const TD_SHIM_SEC_CORE_INFO_BASE: u32 = 0xFFFFFFAC;

// Base Address after Loaded into Memory
pub const TD_SHIM_CONFIG_BASE: u32 = 0xFF000000;
pub const TD_SHIM_MAILBOX_BASE: u32 = 0xFF020000;
pub const TD_SHIM_TEMP_STACK_BASE: u32 = 0xFF021000;
pub const TD_SHIM_TEMP_HEAP_BASE: u32 = 0xFF031000;
pub const TD_SHIM_FREE_BASE: u32 = 0xFF041000;
pub const TD_SHIM_PAYLOAD_BASE: u32 = 0xFF041000;
pub const TD_SHIM_METADATA_BASE: u32 = 0xFFF97000;
pub const TD_SHIM_IPL_BASE: u32 = 0xFFF98000;
pub const TD_SHIM_RESET_VECTOR_BASE: u32 = 0xFFFF8000;
